### ISSUE TITLE
Stop and remove all animations

### ISSUE THREAD

**Issue by Banck** [CosmicMind/Motion#56] opened 2018-10-15 13:20 UTC
Hello!
How can I remove all animations from my view? 
I've tried to do 
`myView.layer.removeAllAnimations()`
But seems it doesn't work properly. I've found method `removeAllMotionAnimations` in your extension for CALayer, but it is marked as internal.

**Comment by Banck** [comment] 2018-10-15 13:25
Um, as I see `removeAllMotionAnimations` just removes all animations from layer, which have prefix "motion". So  `removeAllAnimations()` should works fine, seems my issue in something else.

**Comment by Banck** [comment] 2018-10-15 13:30
I've tried to do 
```
myView.animate(MotionAnimation.fadeOut, MotionAnimation.duration(5), MotionAnimation.completion {
})
myView.layer.removeAllAnimations()
```
but `myView` did the animation anyway.

**Comment by OrkhanAlikhanov** [comment] 2018-10-15 13:32
Hey! Try `development` branch, the issue is fixed in https://github.com/CosmicMind/Motion/commit/14e27b97d09289a69e6ddfa34d8f66c7c22c69ec I believe. View is updated and animations are removed on completion so everything stays in sync.

**Comment by OrkhanAlikhanov** [comment] 2018-10-15 13:35
The reason for `myView.layer.removeAllAnimations()` not removing the animations is that they are not added yet. `animate()` queues animations to be added in main thread.

**Comment by daniel-jonathan** [comment] 2018-10-15 13:39
Thank you @OrkhanAlikhanov, @Banck if you need further help, please reopen or create a new issue.

**Closed as completed by daniel-jonathan** 2018-10-15 13:39 UTC
Labels: help wanted, question, motion, good first issue
